nginx:
  image: nginx:alpine
  links:
    - ihos
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./pass:/etc/nginx/pass
  expose:
    - "8080"

ihos:
  image: propersoft/docker-cd:ihos 
  volumes:
    - ./entrypoint.sh:/entrypoint.sh
    - ./fe-deploy:/opt/ihos
  environment:
    - WORKDIR=/opt/ihos
  expose:
    - "9000"  
    - "8080"     
  entrypoint: /entrypoint.sh
